// Generated by wxt
export {};
declare global {
  const ContentScriptContext: (typeof import("wxt/client"))["ContentScriptContext"];
  const InvalidMatchPattern: (typeof import("wxt/sandbox"))["InvalidMatchPattern"];
  const MatchPattern: (typeof import("wxt/sandbox"))["MatchPattern"];
  const MigrationError: (typeof import("wxt/storage"))["MigrationError"];
  const browser: (typeof import("wxt/browser"))["browser"];
  const createIframeUi: (typeof import("wxt/client"))["createIframeUi"];
  const createIntegratedUi: (typeof import("wxt/client"))["createIntegratedUi"];
  const createShadowRootUi: (typeof import("wxt/client"))["createShadowRootUi"];
  const defineAppConfig: (typeof import("wxt/sandbox"))["defineAppConfig"];
  const defineBackground: (typeof import("wxt/sandbox"))["defineBackground"];
  const defineConfig: (typeof import("wxt"))["defineConfig"];
  const defineContentScript: (typeof import("wxt/sandbox"))["defineContentScript"];
  const defineUnlistedScript: (typeof import("wxt/sandbox"))["defineUnlistedScript"];
  const defineWxtPlugin: (typeof import("wxt/sandbox"))["defineWxtPlugin"];
  const fakeBrowser: (typeof import("wxt/testing"))["fakeBrowser"];
  const injectScript: (typeof import("wxt/client"))["injectScript"];
  const isAgileAvailable: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useBilling"))["isAgileAvailable"];
  const isOrgReadOnly: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useBilling"))["isOrgReadOnly"];
  const setLanguage: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useI18n"))["setLanguage"];
  const storage: (typeof import("wxt/storage"))["storage"];
  const useActionsMenu: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useActionsMenu"))["useActionsMenu"];
  const useApi: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useApi"))["useApi"];
  const useAppConfig: (typeof import("wxt/client"))["useAppConfig"];
  const useAuth: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useAuth"))["useAuth"];
  const useBoardData: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useBoardData"))["useBoardData"];
  const useBoardDerived: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useBoardDerived"))["useBoardDerived"];
  const useBoardDragDrop: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useBoardDragDrop"))["useBoardDragDrop"];
  const useBoardFilters: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useBoardFilters"))["useBoardFilters"];
  const useBoardTaskOps: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useBoardTaskOps"))["useBoardTaskOps"];
  const useI18n: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useI18n"))["useI18n"];
  const useKeyboardShortcuts: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useKeyboardShortcuts"))["useKeyboardShortcuts"];
  const useLocalApi: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useLocalApi"))["useLocalApi"];
  const useNotes: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useNotes"))["useNotes"];
  const useOrgData: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useOrgData"))["useOrgData"];
  const useRefreshCountdown: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useRefreshCountdown"))["useRefreshCountdown"];
  const useScrollSync: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useScrollSync"))["useScrollSync"];
  const useSettings: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useSettings"))["useSettings"];
  const useTheme: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useTheme"))["useTheme"];
  const useWebSocket: (typeof import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useWebSocket"))["useWebSocket"];
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Note } from "/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useNotes";
  import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useNotes");
  // @ts-ignore
  export type {
    OrgType,
    OrgEntry,
  } from "/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useOrgData";
  import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useOrgData");
  // @ts-ignore
  export type { WSMessage } from "/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useWebSocket";
  import("/home/quonaro/CascadeProjects/work/YourTask/yourtask-extension/composables/useWebSocket");
}
